[project]
name = "test-ml-datasphere"
version = "0.1.0"
description = "KMeans Clustering"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
]
